<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.8" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.3.8" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.8" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.8" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Markdown.Avalonia" Version="11.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="ReactiveUI" Version="22.2.1" />
    <PackageReference Include="RtfDomParser" Version="7.0.0" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="System.Reactive.Linq" Version="6.1.0" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="AvRichTextBox">
			<HintPath>lib/AvRichTextBox.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="RtfDomParserAv">
			<HintPath>lib/RtfDomParserAv.dll</HintPath>
		</Reference>
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="AvaloniaEdit">
			<HintPath>lib\AvaloniaEdit.dll</HintPath>
			<Private>true</Private>
			<!-- ensures it’s copied to bin\ on build -->
		</Reference>
	</ItemGroup>


  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Resources\" />
  </ItemGroup>
</Project>
